apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: "Continuous Integration and Continuous Deployment pipeline for GKE applications"
serialPipeline:
  stages:
  - targetId: dev
    # Uncomment if using profiles
    # profiles:
    # - dev
  - targetId: prod
    # Uncomment if using profiles
    # profiles:
    # - prod
